cluster.name: "docker-cluster"
node.name: node-1
network.host: 0.0.0.0
http.port: 9200
discovery.seed_hosts: ["180.210.80.12", "133.186.155.23", "125.6.38.15"]
cluster.initial_master_nodes: ["node_1", "node-2", "node-3"]
node.master: true
node.data: true
