cluster.name: "docker-cluster"
node.name: node_1
network.host: 180.210.80.12
http.port: 9200
discovery.seed_hosts: ["180.210.80.12", "133.186.155.23", "125.6.38.15"]
cluster.initial_master_nodes: ["node_1", "node_2", "node_3"]
node.master: true
node.data: true
node.ingest: true
gateway.recover_after_nodes: 3
