version: '3.7'
services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - mysql-elk
    environment:
      - node.name=node-1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
volumes:
  elasticsearch:

networks:
  mysql-elk:
