version: '3.7'
services:
  mysql:
    build:
      context: mysql/
      args:
        MYSQL_VERSION: $MYSQL_VERSION
    volumes:
      - type: bind
        source: ./mysql/config/mysql.cnf
        target: /etc/mysql/conf.d/my.cnf
        read_only: true
      - type: bind
        source: ./mysql/sql
        target: /docker-entrypoint-initdb.d
        read_only: true  
      - type: volume
        source: mysql
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=d4@]UGI)iVXa/kG6
      - MYSQL_DATABASE=cookshoong_shop_dev
      - MYSQL_USER=cookshoong
      - MYSQL_PASSWORD=d4@]UGI)iVXa/kG6
    networks:
      - mysql-elk

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      discovery.type: single-node
    networks:
      - mysql-elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline/pipelines.yml
        target: /usr/share/logstash/config/pipelines.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline/conf
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash/pipeline/sql
        target: /usr/share/logstash/sql
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xms1g -Xms1g"
    networks:
      - mysql-elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - mysql-elk
    depends_on:
      - elasticsearch

networks:
  mysql-elk:
    driver: bridge

volumes:
  mysql:
  elasticsearch:
