version: '3.7'
services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - mysql-elk
    environment:
      - node.name=node-1
      - discovery.seed_hosts=125.6.38.15:9300,133.186.155.23:9300,180.210.80.12:9300
      - cluster.initial_master_nodes=node-1,node-2,node-3
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
volumes:
  elasticsearch: